package com.zhuxun.dc.apirunner.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DcApiStatisticsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public DcApiStatisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andApiIdIsNull() {
            addCriterion("api_id is null");
            return (Criteria) this;
        }

        public Criteria andApiIdIsNotNull() {
            addCriterion("api_id is not null");
            return (Criteria) this;
        }

        public Criteria andApiIdEqualTo(String value) {
            addCriterion("api_id =", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotEqualTo(String value) {
            addCriterion("api_id <>", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdGreaterThan(String value) {
            addCriterion("api_id >", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdGreaterThanOrEqualTo(String value) {
            addCriterion("api_id >=", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdLessThan(String value) {
            addCriterion("api_id <", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdLessThanOrEqualTo(String value) {
            addCriterion("api_id <=", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdLike(String value) {
            addCriterion("api_id like", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotLike(String value) {
            addCriterion("api_id not like", value, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdIn(List<String> values) {
            addCriterion("api_id in", values, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotIn(List<String> values) {
            addCriterion("api_id not in", values, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdBetween(String value1, String value2) {
            addCriterion("api_id between", value1, value2, "apiId");
            return (Criteria) this;
        }

        public Criteria andApiIdNotBetween(String value1, String value2) {
            addCriterion("api_id not between", value1, value2, "apiId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andApiPathIsNull() {
            addCriterion("api_path is null");
            return (Criteria) this;
        }

        public Criteria andApiPathIsNotNull() {
            addCriterion("api_path is not null");
            return (Criteria) this;
        }

        public Criteria andApiPathEqualTo(String value) {
            addCriterion("api_path =", value, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathNotEqualTo(String value) {
            addCriterion("api_path <>", value, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathGreaterThan(String value) {
            addCriterion("api_path >", value, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathGreaterThanOrEqualTo(String value) {
            addCriterion("api_path >=", value, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathLessThan(String value) {
            addCriterion("api_path <", value, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathLessThanOrEqualTo(String value) {
            addCriterion("api_path <=", value, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathLike(String value) {
            addCriterion("api_path like", value, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathNotLike(String value) {
            addCriterion("api_path not like", value, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathIn(List<String> values) {
            addCriterion("api_path in", values, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathNotIn(List<String> values) {
            addCriterion("api_path not in", values, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathBetween(String value1, String value2) {
            addCriterion("api_path between", value1, value2, "apiPath");
            return (Criteria) this;
        }

        public Criteria andApiPathNotBetween(String value1, String value2) {
            addCriterion("api_path not between", value1, value2, "apiPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathIsNull() {
            addCriterion("proxy_path is null");
            return (Criteria) this;
        }

        public Criteria andProxyPathIsNotNull() {
            addCriterion("proxy_path is not null");
            return (Criteria) this;
        }

        public Criteria andProxyPathEqualTo(String value) {
            addCriterion("proxy_path =", value, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathNotEqualTo(String value) {
            addCriterion("proxy_path <>", value, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathGreaterThan(String value) {
            addCriterion("proxy_path >", value, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathGreaterThanOrEqualTo(String value) {
            addCriterion("proxy_path >=", value, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathLessThan(String value) {
            addCriterion("proxy_path <", value, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathLessThanOrEqualTo(String value) {
            addCriterion("proxy_path <=", value, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathLike(String value) {
            addCriterion("proxy_path like", value, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathNotLike(String value) {
            addCriterion("proxy_path not like", value, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathIn(List<String> values) {
            addCriterion("proxy_path in", values, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathNotIn(List<String> values) {
            addCriterion("proxy_path not in", values, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathBetween(String value1, String value2) {
            addCriterion("proxy_path between", value1, value2, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyPathNotBetween(String value1, String value2) {
            addCriterion("proxy_path not between", value1, value2, "proxyPath");
            return (Criteria) this;
        }

        public Criteria andProxyMethodIsNull() {
            addCriterion("proxy_method is null");
            return (Criteria) this;
        }

        public Criteria andProxyMethodIsNotNull() {
            addCriterion("proxy_method is not null");
            return (Criteria) this;
        }

        public Criteria andProxyMethodEqualTo(String value) {
            addCriterion("proxy_method =", value, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodNotEqualTo(String value) {
            addCriterion("proxy_method <>", value, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodGreaterThan(String value) {
            addCriterion("proxy_method >", value, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodGreaterThanOrEqualTo(String value) {
            addCriterion("proxy_method >=", value, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodLessThan(String value) {
            addCriterion("proxy_method <", value, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodLessThanOrEqualTo(String value) {
            addCriterion("proxy_method <=", value, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodLike(String value) {
            addCriterion("proxy_method like", value, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodNotLike(String value) {
            addCriterion("proxy_method not like", value, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodIn(List<String> values) {
            addCriterion("proxy_method in", values, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodNotIn(List<String> values) {
            addCriterion("proxy_method not in", values, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodBetween(String value1, String value2) {
            addCriterion("proxy_method between", value1, value2, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andProxyMethodNotBetween(String value1, String value2) {
            addCriterion("proxy_method not between", value1, value2, "proxyMethod");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeIsNull() {
            addCriterion("consume_time is null");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeIsNotNull() {
            addCriterion("consume_time is not null");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeEqualTo(Integer value) {
            addCriterion("consume_time =", value, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeNotEqualTo(Integer value) {
            addCriterion("consume_time <>", value, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeGreaterThan(Integer value) {
            addCriterion("consume_time >", value, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("consume_time >=", value, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeLessThan(Integer value) {
            addCriterion("consume_time <", value, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeLessThanOrEqualTo(Integer value) {
            addCriterion("consume_time <=", value, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeIn(List<Integer> values) {
            addCriterion("consume_time in", values, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeNotIn(List<Integer> values) {
            addCriterion("consume_time not in", values, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeBetween(Integer value1, Integer value2) {
            addCriterion("consume_time between", value1, value2, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andConsumeTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("consume_time not between", value1, value2, "consumeTime");
            return (Criteria) this;
        }

        public Criteria andStatusCodeIsNull() {
            addCriterion("status_code is null");
            return (Criteria) this;
        }

        public Criteria andStatusCodeIsNotNull() {
            addCriterion("status_code is not null");
            return (Criteria) this;
        }

        public Criteria andStatusCodeEqualTo(Integer value) {
            addCriterion("status_code =", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotEqualTo(Integer value) {
            addCriterion("status_code <>", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeGreaterThan(Integer value) {
            addCriterion("status_code >", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("status_code >=", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeLessThan(Integer value) {
            addCriterion("status_code <", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeLessThanOrEqualTo(Integer value) {
            addCriterion("status_code <=", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeIn(List<Integer> values) {
            addCriterion("status_code in", values, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotIn(List<Integer> values) {
            addCriterion("status_code not in", values, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeBetween(Integer value1, Integer value2) {
            addCriterion("status_code between", value1, value2, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("status_code not between", value1, value2, "statusCode");
            return (Criteria) this;
        }

        public Criteria andAccessTimeIsNull() {
            addCriterion("access_time is null");
            return (Criteria) this;
        }

        public Criteria andAccessTimeIsNotNull() {
            addCriterion("access_time is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTimeEqualTo(Date value) {
            addCriterion("access_time =", value, "accessTime");
            return (Criteria) this;
        }

        public Criteria andAccessTimeNotEqualTo(Date value) {
            addCriterion("access_time <>", value, "accessTime");
            return (Criteria) this;
        }

        public Criteria andAccessTimeGreaterThan(Date value) {
            addCriterion("access_time >", value, "accessTime");
            return (Criteria) this;
        }

        public Criteria andAccessTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("access_time >=", value, "accessTime");
            return (Criteria) this;
        }

        public Criteria andAccessTimeLessThan(Date value) {
            addCriterion("access_time <", value, "accessTime");
            return (Criteria) this;
        }

        public Criteria andAccessTimeLessThanOrEqualTo(Date value) {
            addCriterion("access_time <=", value, "accessTime");
            return (Criteria) this;
        }

        public Criteria andAccessTimeIn(List<Date> values) {
            addCriterion("access_time in", values, "accessTime");
            return (Criteria) this;
        }

        public Criteria andAccessTimeNotIn(List<Date> values) {
            addCriterion("access_time not in", values, "accessTime");
            return (Criteria) this;
        }

        public Criteria andAccessTimeBetween(Date value1, Date value2) {
            addCriterion("access_time between", value1, value2, "accessTime");
            return (Criteria) this;
        }

        public Criteria andAccessTimeNotBetween(Date value1, Date value2) {
            addCriterion("access_time not between", value1, value2, "accessTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dc_api_statistics
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 15 15:25:27 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}