package com.zhuxun.dc.apirunner.dao.entity;

import java.util.Date;

public class DcApiModelDefinition extends DcApiModelDefinitionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api_model_definition.project_id
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api_model_definition.model_name
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String modelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api_model_definition.model_definition
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String modelDefinition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api_model_definition.model_describe
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String modelDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api_model_definition.create_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api_model_definition.modify_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private Date modifyDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api_model_definition.create_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String createUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api_model_definition.modify_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String modifyUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api_model_definition.project_id
     *
     * @return the value of dc_api_model_definition.project_id
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api_model_definition.project_id
     *
     * @param projectId the value for dc_api_model_definition.project_id
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api_model_definition.model_name
     *
     * @return the value of dc_api_model_definition.model_name
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getModelName() {
        return modelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api_model_definition.model_name
     *
     * @param modelName the value for dc_api_model_definition.model_name
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setModelName(String modelName) {
        this.modelName = modelName == null ? null : modelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api_model_definition.model_definition
     *
     * @return the value of dc_api_model_definition.model_definition
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getModelDefinition() {
        return modelDefinition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api_model_definition.model_definition
     *
     * @param modelDefinition the value for dc_api_model_definition.model_definition
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setModelDefinition(String modelDefinition) {
        this.modelDefinition = modelDefinition == null ? null : modelDefinition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api_model_definition.model_describe
     *
     * @return the value of dc_api_model_definition.model_describe
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getModelDescribe() {
        return modelDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api_model_definition.model_describe
     *
     * @param modelDescribe the value for dc_api_model_definition.model_describe
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setModelDescribe(String modelDescribe) {
        this.modelDescribe = modelDescribe == null ? null : modelDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api_model_definition.create_datetime
     *
     * @return the value of dc_api_model_definition.create_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api_model_definition.create_datetime
     *
     * @param createDatetime the value for dc_api_model_definition.create_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api_model_definition.modify_datetime
     *
     * @return the value of dc_api_model_definition.modify_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public Date getModifyDatetime() {
        return modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api_model_definition.modify_datetime
     *
     * @param modifyDatetime the value for dc_api_model_definition.modify_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setModifyDatetime(Date modifyDatetime) {
        this.modifyDatetime = modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api_model_definition.create_userid
     *
     * @return the value of dc_api_model_definition.create_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api_model_definition.create_userid
     *
     * @param createUserid the value for dc_api_model_definition.create_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setCreateUserid(String createUserid) {
        this.createUserid = createUserid == null ? null : createUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api_model_definition.modify_userid
     *
     * @return the value of dc_api_model_definition.modify_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getModifyUserid() {
        return modifyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api_model_definition.modify_userid
     *
     * @param modifyUserid the value for dc_api_model_definition.modify_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setModifyUserid(String modifyUserid) {
        this.modifyUserid = modifyUserid == null ? null : modifyUserid.trim();
    }
}