package com.zhuxun.dc.apirunner.dao.entity;

import java.util.Date;

public class DcApi extends DcApiKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.api_name
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String apiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.api_operation
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String apiOperation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.api_type
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String apiType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.api_protocol
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String apiProtocol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.api_path
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String apiPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.api_summary
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String apiSummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.project_id
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.folder_id
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String folderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.create_datetime
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.modify_datetime
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private Date modifyDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.create_userid
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String createUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.modify_userid
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private String modifyUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_api.status
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.api_name
     *
     * @return the value of dc_api.api_name
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.api_name
     *
     * @param apiName the value for dc_api.api_name
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.api_operation
     *
     * @return the value of dc_api.api_operation
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getApiOperation() {
        return apiOperation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.api_operation
     *
     * @param apiOperation the value for dc_api.api_operation
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setApiOperation(String apiOperation) {
        this.apiOperation = apiOperation == null ? null : apiOperation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.api_type
     *
     * @return the value of dc_api.api_type
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getApiType() {
        return apiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.api_type
     *
     * @param apiType the value for dc_api.api_type
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setApiType(String apiType) {
        this.apiType = apiType == null ? null : apiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.api_protocol
     *
     * @return the value of dc_api.api_protocol
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getApiProtocol() {
        return apiProtocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.api_protocol
     *
     * @param apiProtocol the value for dc_api.api_protocol
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setApiProtocol(String apiProtocol) {
        this.apiProtocol = apiProtocol == null ? null : apiProtocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.api_path
     *
     * @return the value of dc_api.api_path
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getApiPath() {
        return apiPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.api_path
     *
     * @param apiPath the value for dc_api.api_path
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setApiPath(String apiPath) {
        this.apiPath = apiPath == null ? null : apiPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.api_summary
     *
     * @return the value of dc_api.api_summary
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getApiSummary() {
        return apiSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.api_summary
     *
     * @param apiSummary the value for dc_api.api_summary
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setApiSummary(String apiSummary) {
        this.apiSummary = apiSummary == null ? null : apiSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.project_id
     *
     * @return the value of dc_api.project_id
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.project_id
     *
     * @param projectId the value for dc_api.project_id
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.folder_id
     *
     * @return the value of dc_api.folder_id
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.folder_id
     *
     * @param folderId the value for dc_api.folder_id
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setFolderId(String folderId) {
        this.folderId = folderId == null ? null : folderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.create_datetime
     *
     * @return the value of dc_api.create_datetime
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.create_datetime
     *
     * @param createDatetime the value for dc_api.create_datetime
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.modify_datetime
     *
     * @return the value of dc_api.modify_datetime
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public Date getModifyDatetime() {
        return modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.modify_datetime
     *
     * @param modifyDatetime the value for dc_api.modify_datetime
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setModifyDatetime(Date modifyDatetime) {
        this.modifyDatetime = modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.create_userid
     *
     * @return the value of dc_api.create_userid
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.create_userid
     *
     * @param createUserid the value for dc_api.create_userid
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setCreateUserid(String createUserid) {
        this.createUserid = createUserid == null ? null : createUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.modify_userid
     *
     * @return the value of dc_api.modify_userid
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public String getModifyUserid() {
        return modifyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.modify_userid
     *
     * @param modifyUserid the value for dc_api.modify_userid
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setModifyUserid(String modifyUserid) {
        this.modifyUserid = modifyUserid == null ? null : modifyUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_api.status
     *
     * @return the value of dc_api.status
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_api.status
     *
     * @param status the value for dc_api.status
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}