package com.zhuxun.dc.apirunner.dao.entity;

import java.util.Date;

public class DcDataSchema extends DcDataSchemaKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_data_schema.data_source_id
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String dataSourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_data_schema.database_name
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String databaseName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_data_schema.database_encode
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String databaseEncode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_data_schema.database_sort
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String databaseSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_data_schema.remark
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_data_schema.create_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private Date createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_data_schema.modify_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private Date modifyDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_data_schema.create_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String createUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_data_schema.modify_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String modifyUserid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_data_schema.data_source_id
     *
     * @return the value of dc_data_schema.data_source_id
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getDataSourceId() {
        return dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_data_schema.data_source_id
     *
     * @param dataSourceId the value for dc_data_schema.data_source_id
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setDataSourceId(String dataSourceId) {
        this.dataSourceId = dataSourceId == null ? null : dataSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_data_schema.database_name
     *
     * @return the value of dc_data_schema.database_name
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getDatabaseName() {
        return databaseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_data_schema.database_name
     *
     * @param databaseName the value for dc_data_schema.database_name
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName == null ? null : databaseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_data_schema.database_encode
     *
     * @return the value of dc_data_schema.database_encode
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getDatabaseEncode() {
        return databaseEncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_data_schema.database_encode
     *
     * @param databaseEncode the value for dc_data_schema.database_encode
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setDatabaseEncode(String databaseEncode) {
        this.databaseEncode = databaseEncode == null ? null : databaseEncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_data_schema.database_sort
     *
     * @return the value of dc_data_schema.database_sort
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getDatabaseSort() {
        return databaseSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_data_schema.database_sort
     *
     * @param databaseSort the value for dc_data_schema.database_sort
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setDatabaseSort(String databaseSort) {
        this.databaseSort = databaseSort == null ? null : databaseSort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_data_schema.remark
     *
     * @return the value of dc_data_schema.remark
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_data_schema.remark
     *
     * @param remark the value for dc_data_schema.remark
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_data_schema.create_datetime
     *
     * @return the value of dc_data_schema.create_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public Date getCreateDatetime() {
        return createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_data_schema.create_datetime
     *
     * @param createDatetime the value for dc_data_schema.create_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setCreateDatetime(Date createDatetime) {
        this.createDatetime = createDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_data_schema.modify_datetime
     *
     * @return the value of dc_data_schema.modify_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public Date getModifyDatetime() {
        return modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_data_schema.modify_datetime
     *
     * @param modifyDatetime the value for dc_data_schema.modify_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setModifyDatetime(Date modifyDatetime) {
        this.modifyDatetime = modifyDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_data_schema.create_userid
     *
     * @return the value of dc_data_schema.create_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getCreateUserid() {
        return createUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_data_schema.create_userid
     *
     * @param createUserid the value for dc_data_schema.create_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setCreateUserid(String createUserid) {
        this.createUserid = createUserid == null ? null : createUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_data_schema.modify_userid
     *
     * @return the value of dc_data_schema.modify_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getModifyUserid() {
        return modifyUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_data_schema.modify_userid
     *
     * @param modifyUserid the value for dc_data_schema.modify_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setModifyUserid(String modifyUserid) {
        this.modifyUserid = modifyUserid == null ? null : modifyUserid.trim();
    }
}