package com.zhuxun.dc.apirunner.dao.entity;

import java.util.Date;

public class DcActiveRecord extends DcActiveRecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_active_record.path
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_active_record.operation
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String operation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_active_record.info
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_active_record.access_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private Date accessDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_active_record.access_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String accessUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_active_record.remark
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_active_record.path
     *
     * @return the value of dc_active_record.path
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_active_record.path
     *
     * @param path the value for dc_active_record.path
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_active_record.operation
     *
     * @return the value of dc_active_record.operation
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getOperation() {
        return operation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_active_record.operation
     *
     * @param operation the value for dc_active_record.operation
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setOperation(String operation) {
        this.operation = operation == null ? null : operation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_active_record.info
     *
     * @return the value of dc_active_record.info
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_active_record.info
     *
     * @param info the value for dc_active_record.info
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_active_record.access_datetime
     *
     * @return the value of dc_active_record.access_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public Date getAccessDatetime() {
        return accessDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_active_record.access_datetime
     *
     * @param accessDatetime the value for dc_active_record.access_datetime
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setAccessDatetime(Date accessDatetime) {
        this.accessDatetime = accessDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_active_record.access_userid
     *
     * @return the value of dc_active_record.access_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getAccessUserid() {
        return accessUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_active_record.access_userid
     *
     * @param accessUserid the value for dc_active_record.access_userid
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setAccessUserid(String accessUserid) {
        this.accessUserid = accessUserid == null ? null : accessUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_active_record.remark
     *
     * @return the value of dc_active_record.remark
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_active_record.remark
     *
     * @param remark the value for dc_active_record.remark
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}