package com.zhuxun.dc.apirunner.dao.entity;

public class DcRoute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_route.id
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_route.project_id
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_route.env_id
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    private String envId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_route.path
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_route.url
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_route.retryable
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    private Boolean retryable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dc_route.strip_prefix
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    private Boolean stripPrefix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_route.id
     *
     * @return the value of dc_route.id
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_route.id
     *
     * @param id the value for dc_route.id
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_route.project_id
     *
     * @return the value of dc_route.project_id
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_route.project_id
     *
     * @param projectId the value for dc_route.project_id
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_route.env_id
     *
     * @return the value of dc_route.env_id
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public String getEnvId() {
        return envId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_route.env_id
     *
     * @param envId the value for dc_route.env_id
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public void setEnvId(String envId) {
        this.envId = envId == null ? null : envId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_route.path
     *
     * @return the value of dc_route.path
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_route.path
     *
     * @param path the value for dc_route.path
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_route.url
     *
     * @return the value of dc_route.url
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_route.url
     *
     * @param url the value for dc_route.url
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_route.retryable
     *
     * @return the value of dc_route.retryable
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public Boolean getRetryable() {
        return retryable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_route.retryable
     *
     * @param retryable the value for dc_route.retryable
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public void setRetryable(Boolean retryable) {
        this.retryable = retryable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dc_route.strip_prefix
     *
     * @return the value of dc_route.strip_prefix
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public Boolean getStripPrefix() {
        return stripPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dc_route.strip_prefix
     *
     * @param stripPrefix the value for dc_route.strip_prefix
     *
     * @mbg.generated Wed Jun 13 10:53:49 CST 2018
     */
    public void setStripPrefix(Boolean stripPrefix) {
        this.stripPrefix = stripPrefix;
    }
}