package com.zhuxun.dc.apirunner.dao.mapper;

import com.zhuxun.dc.apirunner.dao.entity.DcApiStatistics;
import com.zhuxun.dc.apirunner.dao.entity.DcApiStatisticsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DcApiStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    long countByExample(DcApiStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    int deleteByExample(DcApiStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    int insert(DcApiStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    int insertSelective(DcApiStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    List<DcApiStatistics> selectByExample(DcApiStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") DcApiStatistics record, @Param("example") DcApiStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_statistics
     *
     * @mbg.generated Fri Jun 15 15:25:27 CST 2018
     */
    int updateByExample(@Param("record") DcApiStatistics record, @Param("example") DcApiStatisticsExample example);
}