package com.zhuxun.dc.apirunner.dao.mapper;

import com.zhuxun.dc.apirunner.dao.entity.DcApiImpl;
import com.zhuxun.dc.apirunner.dao.entity.DcApiImplExample;
import com.zhuxun.dc.apirunner.dao.entity.DcApiImplKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcApiImplMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    long countByExample(DcApiImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByExample(DcApiImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByPrimaryKey(DcApiImplKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insert(DcApiImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insertSelective(DcApiImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    List<DcApiImpl> selectByExample(DcApiImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    DcApiImpl selectByPrimaryKey(DcApiImplKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") DcApiImpl record, @Param("example") DcApiImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExample(@Param("record") DcApiImpl record, @Param("example") DcApiImplExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKeySelective(DcApiImpl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_impl
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKey(DcApiImpl record);
}