package com.zhuxun.dc.apirunner.dao.mapper;

import com.zhuxun.dc.apirunner.dao.entity.DcEnvironment;
import com.zhuxun.dc.apirunner.dao.entity.DcEnvironmentExample;
import com.zhuxun.dc.apirunner.dao.entity.DcEnvironmentKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcEnvironmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    long countByExample(DcEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByExample(DcEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByPrimaryKey(DcEnvironmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insert(DcEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insertSelective(DcEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    List<DcEnvironment> selectByExample(DcEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    DcEnvironment selectByPrimaryKey(DcEnvironmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") DcEnvironment record, @Param("example") DcEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExample(@Param("record") DcEnvironment record, @Param("example") DcEnvironmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKeySelective(DcEnvironment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_environment
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKey(DcEnvironment record);
}