package com.zhuxun.dc.apirunner.dao.mapper;

import com.zhuxun.dc.apirunner.dao.entity.DcActiveRecord;
import com.zhuxun.dc.apirunner.dao.entity.DcActiveRecordExample;
import com.zhuxun.dc.apirunner.dao.entity.DcActiveRecordKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcActiveRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    long countByExample(DcActiveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByExample(DcActiveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByPrimaryKey(DcActiveRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insert(DcActiveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insertSelective(DcActiveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    List<DcActiveRecord> selectByExample(DcActiveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    DcActiveRecord selectByPrimaryKey(DcActiveRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") DcActiveRecord record, @Param("example") DcActiveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExample(@Param("record") DcActiveRecord record, @Param("example") DcActiveRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKeySelective(DcActiveRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_active_record
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKey(DcActiveRecord record);
}