package com.zhuxun.dc.apirunner.dao.mapper;

import com.zhuxun.dc.apirunner.dao.entity.DcApiParam;
import com.zhuxun.dc.apirunner.dao.entity.DcApiParamExample;
import com.zhuxun.dc.apirunner.dao.entity.DcApiParamKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcApiParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    long countByExample(DcApiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByExample(DcApiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByPrimaryKey(DcApiParamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insert(DcApiParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insertSelective(DcApiParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    List<DcApiParam> selectByExample(DcApiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    DcApiParam selectByPrimaryKey(DcApiParamKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") DcApiParam record, @Param("example") DcApiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExample(@Param("record") DcApiParam record, @Param("example") DcApiParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKeySelective(DcApiParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api_param
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKey(DcApiParam record);
}