package com.zhuxun.dc.apirunner.dao.mapper;

import com.zhuxun.dc.apirunner.dao.entity.DcDataSchema;
import com.zhuxun.dc.apirunner.dao.entity.DcDataSchemaExample;
import com.zhuxun.dc.apirunner.dao.entity.DcDataSchemaKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcDataSchemaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    long countByExample(DcDataSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByExample(DcDataSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByPrimaryKey(DcDataSchemaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insert(DcDataSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insertSelective(DcDataSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    List<DcDataSchema> selectByExample(DcDataSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    DcDataSchema selectByPrimaryKey(DcDataSchemaKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") DcDataSchema record, @Param("example") DcDataSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExample(@Param("record") DcDataSchema record, @Param("example") DcDataSchemaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKeySelective(DcDataSchema record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_schema
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKey(DcDataSchema record);
}