package com.zhuxun.dc.apirunner.dao.mapper;

import com.zhuxun.dc.apirunner.dao.entity.DcDataTable;
import com.zhuxun.dc.apirunner.dao.entity.DcDataTableExample;
import com.zhuxun.dc.apirunner.dao.entity.DcDataTableKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcDataTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    long countByExample(DcDataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByExample(DcDataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByPrimaryKey(DcDataTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insert(DcDataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insertSelective(DcDataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    List<DcDataTable> selectByExample(DcDataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    DcDataTable selectByPrimaryKey(DcDataTableKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") DcDataTable record, @Param("example") DcDataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExample(@Param("record") DcDataTable record, @Param("example") DcDataTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKeySelective(DcDataTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_table
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKey(DcDataTable record);
}