package com.zhuxun.dc.apirunner.dao.mapper;

import com.zhuxun.dc.apirunner.dao.entity.DcApi;
import com.zhuxun.dc.apirunner.dao.entity.DcApiExample;
import com.zhuxun.dc.apirunner.dao.entity.DcApiKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcApiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    long countByExample(DcApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    int deleteByExample(DcApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    int deleteByPrimaryKey(DcApiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    int insert(DcApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    int insertSelective(DcApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    List<DcApi> selectByExample(DcApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    DcApi selectByPrimaryKey(DcApiKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") DcApi record, @Param("example") DcApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    int updateByExample(@Param("record") DcApi record, @Param("example") DcApiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    int updateByPrimaryKeySelective(DcApi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_api
     *
     * @mbg.generated Wed May 30 15:17:29 CST 2018
     */
    int updateByPrimaryKey(DcApi record);
}