package com.zhuxun.dc.apirunner.dao.mapper;

import com.zhuxun.dc.apirunner.dao.entity.DcDataColumn;
import com.zhuxun.dc.apirunner.dao.entity.DcDataColumnExample;
import com.zhuxun.dc.apirunner.dao.entity.DcDataColumnKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DcDataColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    long countByExample(DcDataColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByExample(DcDataColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int deleteByPrimaryKey(DcDataColumnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insert(DcDataColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int insertSelective(DcDataColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    List<DcDataColumn> selectByExample(DcDataColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    DcDataColumn selectByPrimaryKey(DcDataColumnKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") DcDataColumn record, @Param("example") DcDataColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByExample(@Param("record") DcDataColumn record, @Param("example") DcDataColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKeySelective(DcDataColumn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dc_data_column
     *
     * @mbg.generated Wed May 30 15:12:35 CST 2018
     */
    int updateByPrimaryKey(DcDataColumn record);
}